/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.lexer;

import java.io.*;
import simpleAdder.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTabulacao(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnter(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEspaco(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBranco(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiroReservada(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRealReservada(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractereReservada(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleanoReservada(line, pos); }
    Token new19(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioDeLinha(text, line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioDeBlocoInicio(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioDeBlocoFim(line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioDeBloco(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSub(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorig(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorig(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreColchete(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreParentese(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaColchete(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaParentese(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoispontos(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontovirgula(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreChave(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaChave(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNao(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new46(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(text, line, pos); }
    Token new47(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(text, line, pos); }
    Token new48(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(text, line, pos); }
    Token new49(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBooleano(text, line, pos); }
    Token new50(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVetor(text, line, pos); }
    Token new51(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipo(text, line, pos); }
    Token new52(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {47, 47, 12}, {48, 57, 13}, {58, 58, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {91, 91, 20}, {93, 93, 21}, {95, 95, 22}, {97, 97, 23}, {98, 98, 24}, {99, 99, 25}, {100, 100, 19}, {101, 101, 26}, {102, 102, 27}, {103, 104, 19}, {105, 105, 28}, {106, 107, 19}, {108, 108, 29}, {109, 109, 19}, {110, 110, 30}, {111, 111, 31}, {112, 112, 32}, {113, 113, 19}, {114, 114, 33}, {115, 115, 34}, {116, 117, 19}, {118, 118, 35}, {119, 122, 19}, {123, 123, 36}, {125, 125, 37}, },
            {},
            {},
            {{10, 10, 38}, },
            {},
            {{65, 90, 39}, {97, 122, 39}, },
            {},
            {},
            {{47, 47, 40}, },
            {{48, 57, 41}, },
            {},
            {{48, 57, 42}, },
            {{42, 42, 43}, {47, 47, 44}, },
            {{44, 44, 45}, {48, 57, 13}, },
            {{61, 61, 46}, },
            {},
            {{61, 61, 47}, {62, 62, 48}, },
            {},
            {{61, 61, 49}, },
            {{48, 57, 50}, {65, 90, 51}, {95, 95, 52}, {97, 122, 51}, },
            {{39, 39, 53}, {43, 43, 54}, {45, 45, 55}, {48, 57, 56}, {102, 102, 57}, {118, 118, 58}, },
            {},
            {{48, 57, 59}, {65, 90, 60}, {95, 95, 61}, {97, 122, 60}, },
            {{48, 95, -21}, {97, 117, 51}, {118, 118, 62}, {119, 122, 51}, },
            {{48, 95, -21}, {97, 110, 51}, {111, 111, 63}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 97, 64}, {98, 122, 51}, },
            {{48, 95, -21}, {97, 109, 51}, {110, 110, 65}, {111, 114, 51}, {115, 115, 66}, {116, 122, 51}, },
            {{48, 95, -21}, {97, 97, 67}, {98, 104, 51}, {105, 105, 68}, {106, 122, 51}, },
            {{48, 109, -28}, {110, 110, 69}, {111, 122, 51}, },
            {{48, 95, -21}, {97, 100, 51}, {101, 101, 70}, {102, 122, 51}, },
            {{48, 95, -21}, {97, 97, 71}, {98, 122, 51}, },
            {{48, 95, -21}, {97, 116, 51}, {117, 117, 72}, {118, 122, 51}, },
            {{48, 95, -21}, {97, 97, 73}, {98, 113, 51}, {114, 114, 74}, {115, 122, 51}, },
            {{48, 100, -31}, {101, 101, 75}, {102, 122, 51}, },
            {{48, 100, -31}, {101, 101, 76}, {102, 122, 51}, },
            {{48, 100, -31}, {101, 101, 77}, {102, 122, 51}, },
            {},
            {},
            {},
            {{39, 39, 78}, },
            {},
            {{44, 44, 45}, {48, 57, 41}, },
            {{44, 44, 45}, {48, 57, 42}, },
            {{0, 41, 79}, {42, 42, 80}, {43, 255, 79}, },
            {{0, 9, 81}, {11, 255, 81}, },
            {{48, 57, 82}, },
            {},
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{65, 90, 83}, {97, 122, 83}, },
            {{48, 57, 84}, },
            {{48, 57, 85}, },
            {{44, 44, 86}, {48, 57, 56}, {59, 59, 87}, {93, 93, 88}, },
            {{97, 97, 89}, },
            {{101, 101, 90}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -21}, {97, 97, 91}, {98, 122, 51}, },
            {{48, 110, -26}, {111, 111, 92}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 113, 51}, {114, 114, 93}, {115, 115, 94}, {116, 122, 51}, },
            {{48, 95, -21}, {97, 112, 51}, {113, 113, 95}, {114, 122, 51}, },
            {{48, 95, -21}, {97, 98, 51}, {99, 99, 96}, {100, 122, 51}, },
            {{48, 95, -21}, {97, 107, 51}, {108, 108, 97}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 108, 51}, {109, 109, 98}, {110, 122, 51}, },
            {{48, 95, -21}, {97, 104, 51}, {105, 105, 99}, {106, 115, 51}, {116, 116, 100}, {117, 122, 51}, },
            {{48, 104, -71}, {105, 105, 101}, {106, 122, 51}, },
            {{48, 110, -26}, {111, 111, 102}, {112, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 113, -66}, {114, 114, 103}, {115, 122, 51}, },
            {{48, 110, -26}, {111, 111, 104}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 97, 105}, {98, 122, 51}, },
            {{48, 109, -28}, {110, 110, 106}, {111, 122, 51}, },
            {{48, 113, -66}, {114, 114, 107}, {115, 122, 51}, },
            {},
            {{0, 255, -45}, },
            {{0, 42, -45}, {43, 46, 79}, {47, 47, 108}, {48, 255, 79}, },
            {{0, 255, -46}, },
            {{48, 57, 82}, },
            {{39, 39, 109}, },
            {{44, 44, 86}, {48, 57, 84}, {59, 93, -58}, },
            {{44, 44, 86}, {48, 57, 85}, {59, 93, -58}, },
            {{48, 57, 110}, },
            {{43, 43, 111}, {45, 45, 112}, {48, 57, 113}, },
            {},
            {{108, 108, 114}, },
            {{114, 114, 115}, },
            {{48, 107, -69}, {108, 108, 116}, {109, 122, 51}, },
            {{48, 107, -69}, {108, 108, 117}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 97, 118}, {98, 122, 51}, },
            {{48, 110, -26}, {111, 111, 119}, {112, 122, 51}, },
            {{48, 116, -33}, {117, 117, 120}, {118, 122, 51}, },
            {{48, 113, -66}, {114, 114, 121}, {115, 122, 51}, },
            {{48, 95, -21}, {97, 114, 51}, {115, 115, 122}, {116, 122, 51}, },
            {{46, 46, 123}, {48, 122, -21}, },
            {{48, 98, -68}, {99, 99, 124}, {100, 122, 51}, },
            {{48, 100, -31}, {101, 101, 125}, {102, 122, 51}, },
            {{48, 95, -21}, {97, 97, 126}, {98, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 127}, {98, 122, 51}, },
            {{48, 95, -21}, {97, 102, 51}, {103, 103, 128}, {104, 122, 51}, },
            {{48, 107, -69}, {108, 108, 129}, {109, 122, 51}, },
            {{48, 95, -21}, {97, 97, 130}, {98, 122, 51}, },
            {{48, 95, -21}, {97, 99, 51}, {100, 100, 131}, {101, 122, 51}, },
            {{0, 255, -45}, },
            {{59, 59, 132}, {93, 93, 88}, },
            {{48, 57, 110}, {59, 59, 133}, {93, 93, 88}, },
            {{48, 57, 134}, },
            {{48, 57, 135}, },
            {{48, 57, 113}, {59, 93, -58}, },
            {{115, 115, 136}, },
            {{100, 100, 137}, },
            {{48, 104, -71}, {105, 105, 138}, {106, 122, 51}, },
            {{48, 100, -31}, {101, 101, 139}, {102, 122, 51}, },
            {{48, 98, -68}, {99, 99, 140}, {100, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 141}, {98, 122, 51}, },
            {{48, 100, -31}, {101, 101, 142}, {102, 122, 51}, },
            {{48, 110, -26}, {111, 111, 143}, {112, 122, 51}, },
            {},
            {{48, 104, -71}, {105, 105, 144}, {106, 122, 51}, },
            {{48, 104, -71}, {105, 105, 145}, {106, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 113, -66}, {114, 114, 146}, {115, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 110, -26}, {111, 111, 147}, {112, 122, 51}, },
            {{48, 95, -21}, {97, 97, 148}, {98, 122, 51}, },
            {{39, 39, 149}, },
            {{43, 43, 150}, {45, 45, 151}, {48, 57, 152}, },
            {{48, 57, 134}, {59, 93, -58}, },
            {{48, 57, 135}, {59, 93, -58}, },
            {{111, 111, 153}, },
            {{97, 97, 154}, },
            {{48, 100, -31}, {101, 101, 155}, {102, 122, 51}, },
            {{48, 95, -21}, {97, 97, 156}, {98, 122, 51}, },
            {{48, 95, -21}, {97, 115, 51}, {116, 116, 157}, {117, 122, 51}, },
            {{48, 109, -28}, {110, 110, 158}, {111, 122, 51}, },
            {{48, 117, -25}, {118, 118, 159}, {119, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 110, -26}, {111, 111, 160}, {112, 122, 51}, },
            {{48, 113, -66}, {114, 114, 161}, {115, 122, 51}, },
            {{48, 95, -21}, {97, 97, 162}, {98, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 99, -109}, {100, 100, 163}, {101, 122, 51}, },
            {{65, 90, 164}, {97, 122, 164}, },
            {{48, 57, 165}, },
            {{48, 57, 166}, },
            {{44, 44, 167}, {48, 57, 152}, },
            {{59, 59, 168}, {93, 93, 88}, },
            {{100, 100, 169}, },
            {{48, 122, -21}, },
            {{48, 109, -28}, {110, 110, 170}, {111, 122, 51}, },
            {{48, 100, -31}, {101, 101, 171}, {102, 122, 51}, },
            {{48, 115, -142}, {116, 116, 172}, {117, 122, 51}, },
            {{48, 95, -21}, {97, 97, 173}, {98, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 110, -26}, {111, 111, 174}, {112, 122, 51}, },
            {{48, 108, -70}, {109, 109, 175}, {110, 122, 51}, },
            {{48, 100, -31}, {101, 101, 176}, {102, 122, 51}, },
            {{39, 39, 177}, },
            {{44, 44, 167}, {48, 57, 165}, },
            {{44, 44, 167}, {48, 57, 166}, },
            {{48, 57, 178}, },
            {{102, 102, 179}, {118, 118, 180}, },
            {{101, 101, 181}, },
            {{48, 110, -26}, {111, 111, 182}, {112, 122, 51}, },
            {{48, 113, -66}, {114, 114, 183}, {115, 122, 51}, },
            {{48, 110, -26}, {111, 111, 184}, {112, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 185}, {98, 122, 51}, },
            {{48, 104, -71}, {105, 105, 186}, {106, 122, 51}, },
            {{59, 93, -111}, },
            {{48, 57, 178}, {59, 93, -112}, },
            {{97, 97, 187}, },
            {{101, 101, 188}, },
            {{105, 105, 189}, },
            {{48, 122, -21}, },
            {{48, 100, -31}, {101, 101, 190}, {102, 122, 51}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 113, -66}, {114, 114, 191}, {115, 122, 51}, },
            {{108, 108, 192}, },
            {{114, 114, 193}, },
            {{114, 114, 194}, },
            {{48, 122, -21}, },
            {{48, 110, -26}, {111, 111, 195}, {112, 122, 51}, },
            {{115, 115, 196}, },
            {{100, 100, 197}, },
            {{111, 111, 198}, },
            {{48, 122, -21}, },
            {{111, 111, 199}, },
            {{97, 97, 200}, },
            {{59, 93, -155}, },
            {{59, 93, -155}, },
            {{100, 100, 201}, },
            {{101, 101, 202}, },
            {{105, 105, 203}, },
            {{114, 114, 204}, },
            {{111, 111, 205}, },
            {{59, 93, -155}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 0, 1, 1, 2, -1, 34, 36, 25, 23, 40, 24, 26, 46, 38, 39, 32, 27, 31, 52, 33, 35, -1, 52, 52, 52, 45, 52, 52, 52, 52, 52, 52, 52, 52, 52, 41, 42, 1, -1, 21, 46, 46, 20, 19, -1, 37, 30, 28, 29, 52, 52, 52, -1, -1, -1, -1, -1, -1, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 44, 52, 52, 52, 5, 52, 48, -1, -1, 19, 47, -1, -1, -1, -1, -1, 50, -1, -1, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 43, 52, 52, 52, 52, 52, 22, -1, -1, -1, -1, -1, -1, -1, 52, 52, 52, 12, 52, 52, 52, 8, 52, 52, 13, 10, 52, 16, 52, 52, -1, -1, -1, -1, -1, -1, 52, 52, 52, 52, 52, 49, 52, 52, 52, 6, 52, -1, -1, -1, -1, -1, -1, 11, 52, 52, 52, 52, 7, 52, 52, 52, -1, -1, -1, -1, -1, -1, 52, 52, 52, 14, 15, 52, 52, -1, -1, -1, -1, -1, 18, 52, 9, 4, 52, -1, -1, -1, 17, 52, -1, -1, -1, 49, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
