/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoPalavraTipo extends PTipo
{
    private TBooleanoReservada _booleanoReservada_;

    public ABooleanoPalavraTipo()
    {
        // Constructor
    }

    public ABooleanoPalavraTipo(
        @SuppressWarnings("hiding") TBooleanoReservada _booleanoReservada_)
    {
        // Constructor
        setBooleanoReservada(_booleanoReservada_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoPalavraTipo(
            cloneNode(this._booleanoReservada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoPalavraTipo(this);
    }

    public TBooleanoReservada getBooleanoReservada()
    {
        return this._booleanoReservada_;
    }

    public void setBooleanoReservada(TBooleanoReservada node)
    {
        if(this._booleanoReservada_ != null)
        {
            this._booleanoReservada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanoReservada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanoReservada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanoReservada_ == child)
        {
            this._booleanoReservada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanoReservada_ == oldChild)
        {
            setBooleanoReservada((TBooleanoReservada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
