/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ACaracterPalavraTipo extends PTipo
{

    public ACaracterPalavraTipo()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ACaracterPalavraTipo();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaracterPalavraTipo(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
