/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AEUmVarLogicaAnd extends PLogicaAnd
{
    private PLogicaAnd _logicaAnd_;
    private TE _e_;
    private PVar _var_;

    public AEUmVarLogicaAnd()
    {
        // Constructor
    }

    public AEUmVarLogicaAnd(
        @SuppressWarnings("hiding") PLogicaAnd _logicaAnd_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PVar _var_)
    {
        // Constructor
        setLogicaAnd(_logicaAnd_);

        setE(_e_);

        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new AEUmVarLogicaAnd(
            cloneNode(this._logicaAnd_),
            cloneNode(this._e_),
            cloneNode(this._var_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEUmVarLogicaAnd(this);
    }

    public PLogicaAnd getLogicaAnd()
    {
        return this._logicaAnd_;
    }

    public void setLogicaAnd(PLogicaAnd node)
    {
        if(this._logicaAnd_ != null)
        {
            this._logicaAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaAnd_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaAnd_)
            + toString(this._e_)
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaAnd_ == child)
        {
            this._logicaAnd_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaAnd_ == oldChild)
        {
            setLogicaAnd((PLogicaAnd) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
