/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AMenorigualOpRelacional extends POpRelacional
{
    private TMenorig _menorig_;

    public AMenorigualOpRelacional()
    {
        // Constructor
    }

    public AMenorigualOpRelacional(
        @SuppressWarnings("hiding") TMenorig _menorig_)
    {
        // Constructor
        setMenorig(_menorig_);

    }

    @Override
    public Object clone()
    {
        return new AMenorigualOpRelacional(
            cloneNode(this._menorig_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorigualOpRelacional(this);
    }

    public TMenorig getMenorig()
    {
        return this._menorig_;
    }

    public void setMenorig(TMenorig node)
    {
        if(this._menorig_ != null)
        {
            this._menorig_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorig_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menorig_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menorig_ == child)
        {
            this._menorig_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menorig_ == oldChild)
        {
            setMenorig((TMenorig) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
