/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ANegacaoLogicaXor extends PLogicaXor
{
    private PLogicaNeg _logicaNeg_;

    public ANegacaoLogicaXor()
    {
        // Constructor
    }

    public ANegacaoLogicaXor(
        @SuppressWarnings("hiding") PLogicaNeg _logicaNeg_)
    {
        // Constructor
        setLogicaNeg(_logicaNeg_);

    }

    @Override
    public Object clone()
    {
        return new ANegacaoLogicaXor(
            cloneNode(this._logicaNeg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegacaoLogicaXor(this);
    }

    public PLogicaNeg getLogicaNeg()
    {
        return this._logicaNeg_;
    }

    public void setLogicaNeg(PLogicaNeg node)
    {
        if(this._logicaNeg_ != null)
        {
            this._logicaNeg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaNeg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaNeg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaNeg_ == child)
        {
            this._logicaNeg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaNeg_ == oldChild)
        {
            setLogicaNeg((PLogicaNeg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
