/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AVariasDeclExp extends PDeclExp
{
    private PExp _exp_;
    private PDeclExp _declExp_;

    public AVariasDeclExp()
    {
        // Constructor
    }

    public AVariasDeclExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PDeclExp _declExp_)
    {
        // Constructor
        setExp(_exp_);

        setDeclExp(_declExp_);

    }

    @Override
    public Object clone()
    {
        return new AVariasDeclExp(
            cloneNode(this._exp_),
            cloneNode(this._declExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasDeclExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PDeclExp getDeclExp()
    {
        return this._declExp_;
    }

    public void setDeclExp(PDeclExp node)
    {
        if(this._declExp_ != null)
        {
            this._declExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._declExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._declExp_ == child)
        {
            this._declExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._declExp_ == oldChild)
        {
            setDeclExp((PDeclExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
