/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AVariasDeclVarSempontov extends PDeclVarSempontov
{
    private PVar _var_;
    private TVirgula _virgula_;
    private PDeclVarSempontov _declVarSempontov_;

    public AVariasDeclVarSempontov()
    {
        // Constructor
    }

    public AVariasDeclVarSempontov(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PDeclVarSempontov _declVarSempontov_)
    {
        // Constructor
        setVar(_var_);

        setVirgula(_virgula_);

        setDeclVarSempontov(_declVarSempontov_);

    }

    @Override
    public Object clone()
    {
        return new AVariasDeclVarSempontov(
            cloneNode(this._var_),
            cloneNode(this._virgula_),
            cloneNode(this._declVarSempontov_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasDeclVarSempontov(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PDeclVarSempontov getDeclVarSempontov()
    {
        return this._declVarSempontov_;
    }

    public void setDeclVarSempontov(PDeclVarSempontov node)
    {
        if(this._declVarSempontov_ != null)
        {
            this._declVarSempontov_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declVarSempontov_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._virgula_)
            + toString(this._declVarSempontov_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._declVarSempontov_ == child)
        {
            this._declVarSempontov_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._declVarSempontov_ == oldChild)
        {
            setDeclVarSempontov((PDeclVarSempontov) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
