/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AXorVarLogicaXor extends PLogicaXor
{
    private PVar _l_;
    private TXor _xor_;
    private PVar _r_;

    public AXorVarLogicaXor()
    {
        // Constructor
    }

    public AXorVarLogicaXor(
        @SuppressWarnings("hiding") PVar _l_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PVar _r_)
    {
        // Constructor
        setL(_l_);

        setXor(_xor_);

        setR(_r_);

    }

    @Override
    public Object clone()
    {
        return new AXorVarLogicaXor(
            cloneNode(this._l_),
            cloneNode(this._xor_),
            cloneNode(this._r_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXorVarLogicaXor(this);
    }

    public PVar getL()
    {
        return this._l_;
    }

    public void setL(PVar node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PVar getR()
    {
        return this._r_;
    }

    public void setR(PVar node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._xor_)
            + toString(this._r_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PVar) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
