/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TAbreColcheteReservada extends Token
{
    public TAbreColcheteReservada()
    {
        super.setText("abre_colchete");
    }

    public TAbreColcheteReservada(int line, int pos)
    {
        super.setText("abre_colchete");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAbreColcheteReservada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAbreColcheteReservada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAbreColcheteReservada text.");
    }
}
