/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TComentarioDeLinhaReservada extends Token
{
    public TComentarioDeLinhaReservada()
    {
        super.setText("comentario_de_linha");
    }

    public TComentarioDeLinhaReservada(int line, int pos)
    {
        super.setText("comentario_de_linha");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComentarioDeLinhaReservada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComentarioDeLinhaReservada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComentarioDeLinhaReservada text.");
    }
}
