/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TIdReservada extends Token
{
    public TIdReservada()
    {
        super.setText("id");
    }

    public TIdReservada(int line, int pos)
    {
        super.setText("id");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdReservada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdReservada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIdReservada text.");
    }
}
