/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TNRealReservada extends Token
{
    public TNRealReservada()
    {
        super.setText("n_real");
    }

    public TNRealReservada(int line, int pos)
    {
        super.setText("n_real");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNRealReservada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNRealReservada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNRealReservada text.");
    }
}
