/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TSomaReservada extends Token
{
    public TSomaReservada()
    {
        super.setText("soma");
    }

    public TSomaReservada(int line, int pos)
    {
        super.setText("soma");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSomaReservada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSomaReservada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSomaReservada text.");
    }
}
